module.exports = {
  article:{'entry':'./src/views/article/article.js','output':'../dist/article.html'},
  contentDetail: {'entry': './src/views/article/ContentDetail.js', 'output': '../dist/content_detail.html'},
  bannerDetail: {'entry': './src/views/banner/BannerDetail.js', 'output': '../dist/banner_detail.html'},
  category2: {'entry': './src/views/category/category2.js', 'output': '../dist/category2.html'},
  collect:{'entry':'./src/views/collect/collect.js','output':'../dist/collect.html'},
  coupons:{'entry':'./src/views/coupons/coupons.js','output':'../dist/coupons.html'},
  choiceCoupons: {'entry': './src/views/coupons/ChoiceCoupons.js', 'output': '../dist/choice_coupons.html'},
  feedback: {'entry': './src/views/feedback/feedback.js', 'output': '../dist/feedback.html'},
  furnitureList: {'entry': './src/views/furniturelist/FurnitureList.js', 'output': '../dist/furniturelist.html'},
  goodsList2: {'entry': './src/views/goodsList/goodsList2.js', 'output': '../dist/goods_list2.html'},
  helpCenter:{'entry':'./src/views/helpCenter/HelpCenter.js','output':'../dist/help_center.html'},
  home: {'entry': './src/views/home/home.js', 'output': '../dist/index.html'},
  like: {'entry': './src/views/like/like.js', 'output': '../dist/like.html'},
  likeList: {'entry': './src/views/like/LikeList.js', 'output': '../dist/like_list.html'},
  likeDetails: {'entry': './src/views/like/LikeDetails.js', 'output': '../dist/like_details.html'},
  members: {'entry': './src/views/members/members.js', 'output': '../dist/members.html'},
  appraiseWait: {'entry': './src/views/myOrder/AppraiseWait.js', 'output': '../dist/appraise_wait.html'},
  comment: {'entry': './src/views/myOrder/comment.js', 'output': '../dist/comment.html'},
  commentContent: {'entry': './src/views/myOrder/commentContent.js', 'output': '../dist/comment_content.html'},
  logistical: {'entry': './src/views/myOrder/logistical.js', 'output': '../dist/logistical.html'},
  orderDetails: {'entry': './src/views/myOrder/OrderDetails.js', 'output': '../dist/order_details.html'},
  orderInformationWait: {'entry': './src/views/myOrder/OrderInformationWait.js', 'output': '../dist/orderInformation_wait.html'},
  orderList: {'entry': './src/views/myOrder/OrderList.js', 'output': '../dist/order_list.html'},
  receiveGoodsWait: {'entry': './src/views/myOrder/ReceiveGoodsWait.js', 'output': '../dist/receiveGoods_wait.html'},
  returnGoods: {'entry': './src/views/myOrder/ReturnGoods.js', 'output': '../dist/return_goods.html'},
  service: {'entry': './src/views/myOrder/service.js', 'output': '../dist/service.html'},
  confirmOrder:{'entry':'./src/views/order/ConfirmOrder.js','output':'../dist/confirm_order.html'},
  paySuccsee: {'entry': './src/views/order/PaySuccess.js', 'output': '../dist/pay_success.html'},
  personalCenter:{'entry':'./src/views/personalCenter/personalCenter.js','output':'../dist/personal_center.html'},
  praiseGoodsDetail: {'entry': './src/views/praise/PraiseGoodsDetail.js', 'output': '../dist/praise_goods_detail.html'},
  afterSaleInformation: {'entry': './src/views/productInformation/afterSaleInformation.js', 'output': '../dist/afterSale_information.html'},
  productCommentaries: {'entry': './src/views/productInformation/ProductCommentaries.js', 'output': '../dist/product_commentaries.html'},
  productInformation:{'entry':'./src/views/productInformation/ProductInformation.js','output':'../dist/product_information.html'},
  publishCommentaries: {'entry': './src/views/productInformation/PublishCommentaries.js', 'output': '../dist/publish_commentaries.html'},
  addReceiverAddress: {'entry': './src/views/receiverAddress/AddReceiverAddress.js', 'output': '../dist/add_receiver_address.html'},
  editReceiverAddress: {'entry': './src/views/receiverAddress/EditReceiverAddress.js', 'output': '../dist/edit_receiver_address.html'},
  receiverAddress: {'entry': './src/views/receiverAddress/ReceiverAddress.js', 'output': '../dist/receiver_address.html'},
  designer: {'entry': './src/views/scene/designer.js', 'output': '../dist/designer.html'},
  learnMore: {'entry': './src/views/scene/learnMore.js', 'output': '../dist/learn_more.html'},
  newscenePicture: {'entry': './src/views/scene/newScenePicture.js', 'output': '../dist/newscene.html'},
  scenePicture: {'entry': './src/views/scene/ScenePicture.js', 'output': '../dist/scene.html'},
  sceneFurniture: {'entry': './src/views/sceneFurniture/sceneFurniture.js', 'output': '../dist/furniture_scene.html'},
  sceneList:{'entry':'./src/views/sceneList/SceneList.js','output':'../dist/scene_list.html'},
  sceneList2: {'entry': './src/views/sceneList/sceneList2.js', 'output': '../dist/home_sceneList.html'},
  picSearchResult: {'entry': './src/views/search/picSearchResult.js', 'output': '../dist/pic_result.html'},
  searchResult: {'entry': './src/views/search/searchResult.js', 'output': '../dist/search_result.html'},
  shoppingCart:{'entry':'./src/views/shoppingCart/ShoppingCart.js','output':'../dist/shopping_cart.html'},
  shopwindowdetail2: {'entry': './src/views/shopwindowdetail/shopwindowdetail2.js', 'output': '../dist/shopwindowdetail2.html'},
  shopwindowlist: {'entry': './src/views/shopwindowlist/shopwindowlist.js', 'output': '../dist/shopwindowlist.html'},
  spaceDetail: {'entry': './src/views/space/SpaceDetail.js', 'output': '../dist/space_detail.html'},
  goodsDetail: {'entry': './src/views/productInformation/goodsDetail.js', 'output': '../dist/goods_detail.html'},
  planDetail: {'entry': './src/views/plan/planDetail.js', 'output': '../dist/plan_detail.html'},
  newComers: {'entry': './src/views/gift/newComers.js', 'output': '../dist/newcomers_gift.html'},
  planActivity: {'entry': './src/views/plan/planActivity.js', 'output': '../dist/plan_activity.html'},
  share: {'entry': './src/views/gift/share.js', 'output': '../dist/share.html'},
  softWearActivity: {'entry': './src/views/plan/softWearActivity.js', 'output': '../dist/softWear_activity.html'},
  shareToFriend: {'entry': './src/views/gift/shareToFriend.js', 'output': '../dist/share_to_friend.html'},
  planReceive: {'entry': './src/views/plan/planReceive.js', 'output': '../dist/plan_receive.html'},
  help: {'entry': './src/views/helpCenter/help.js', 'output': '../dist/help.html'},
  sendProblem: {'entry': './src/views/helpCenter/sendProblem.js', 'output': '../dist/send_problem.html'},
  orderProblem: {'entry': './src/views/helpCenter/orderProblem.js', 'output': '../dist/order_problem.html'},
  aftersaleProblem: {'entry': './src/views/helpCenter/aftersaleProblem.js', 'output': '../dist/aftersale_problem.html'},
  priceProblem: {'entry': './src/views/helpCenter/priceProblem.js', 'output': '../dist/price_problem.html'},
  normalProblem: {'entry': './src/views/helpCenter/normalProblem.js', 'output': '../dist/normal_problem.html'},
  messageCenter: {'entry': './src/views/messageCenter/messageCenter.js', 'output': '../dist/message_center.html'},
  messageCenterDetail: {'entry': './src/views/messageCenter/messageCenterDetail.js', 'output': '../dist/message_center_detail.html'},
  planList: {'entry': './src/views/sceneList/planList.js', 'output': '../dist/plan_list.html'},
  hotel: {'entry': './src/views/hotel/hotel.js', 'output': '../dist/hotel.html'},
  bankActivity: {'entry': './src/views/gift/bankActivity.js', 'output': '../dist/bank_activity.html'}
}
